c_stdlib_version:          # [osx]
  - 11.0                   # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - '12.3'                 # [osx]

c_compiler:    # [win]
  - vs2022       # [win]
cxx_compiler:  # [win]
  - vs2022       # [win]
