{% set version = "5.9.1" %}
{% set maj_min = ".".join(version.split(".")[:2]) %}
{% set build_num = 2 %}

package:
  name: paraview{{ build_variant }}
  version: {{ version }}

source:
  url: https://paraview.org/files/v{{ maj_min }}/ParaView-v{{ version }}.tar.xz
  md5: 8bb6e0eca272b570ea28e3f7db8574a4
  patches:
    # https://gitlab.freedesktop.org/mesa/mesa/-/issues/4729
    - shader_init.patch

{% if build_variant == "qt" %}
{% set build_num = build_num + 100 %}
{% endif %}

build:
  number: {{ build_num }}
  skip: true  # [win]
  {% if build_variant == "egl" %}
  skip: true  # [osx]
  {% endif %}
  string: h{{ PKG_HASH }}_{{ build_num }}_{{ build_variant }}
  track_features:
    - paraview-egl   # [build_variant == "egl"]
  run_exports:
    - {{ pin_subpackage('paraview', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - eigen
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('mesa-libgbm') }}           # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxrandr') }}             # [linux]
    - {{ cdt('alsa-lib') }}              # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
    - {{ cdt('libxt-devel') }}           # [linux]
    - {{ cdt('libsm-devel') }}           # [linux]
    - {{ cdt('libice-devel') }}          # [linux]
    - {{ cdt('libuuid-devel') }}         # [linux]
  host:
    - python
    - hdf5
    - libpng
    - jpeg
    - libtiff
    - libxml2
    - zlib
    - freetype
    - libprotobuf
    - lz4-c
    - expat
    - libnetcdf
    - glew
    - double-conversion
    - jsoncpp
    - xz
    - cgns
    - boost-cpp
    - pugixml
    - libtheora
    - gl2ps
    {% if build_variant == "qt" %}
    - qt
    {% endif %}
  run:
    - python
    - numpy
    - matplotlib-base
    - twisted

test:
  imports:
    - paraview
    - paraview.collaboration
    - paraview.coprocessing
    - paraview.lookuptable
    - paraview.numeric
    - paraview.numpy_support
    - paraview.python_view
    - paraview.servermanager
    - paraview.simple
    - paraview.util

  commands:
    - python -c "from paraview.simple import VisItNek5000Reader"
    - python -c "from paraview.simple import Xdmf3ReaderS"
    - pvpython --version
    - paraview --version  # [not linux]

about:
  home: http://www.paraview.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: Copyright.txt
  summary: ParaView is an open-source, multi-platform data analysis and visualization application based on Visualization Toolkit (VTK).

extra:
  recipe-maintainers:
    - bgruening
    - jschueller
