{% set version = "5.7.1" %}
{% set maj_min = ".".join(version.split(".")[:2]) %}

package:
  name: paraview
  version: {{ version }}

source:
  fn: ParaView-v{{ version }}.tar.gz
  url: http://paraview.org/files/v{{ maj_min }}/ParaView-v5.7.0.tar.gz
  md5: ab58b1adf137f72d642a9effc4855292
  patches:
    # py38 support: https://gitlab.kitware.com/vtk/vtk/merge_requests/5883
    - MR5883.patch
    # missing opengl link: https://gitlab.kitware.com/vtk/vtk/merge_requests/5734
    - MR5734.patch

build:
  number: 1
  skip: true  # [win and vc<14]
  skip: true  # [py2k]
  run_exports:
    - {{ pin_subpackage('paraview', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - eigen
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxrandr') }}             # [linux]
    - {{ cdt('alsa-lib') }}              # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
    - {{ cdt('libxt-devel') }}           # [linux]
    - {{ cdt('libsm-devel') }}           # [linux]
    - {{ cdt('libice-devel') }}          # [linux]
    - {{ cdt('libuuid-devel') }}         # [linux]
  host:
    - python
    - hdf5
    - libpng
    - jpeg
    - libtiff
    - libxml2
    - zlib
    - freetype
    - libprotobuf
    - lz4-c
    - expat
    - libnetcdf
    - glew
    - double-conversion
    - jsoncpp
    - xz
    - cgns
    - qt
  run:
    - python
    - numpy
    - matplotlib
    - twisted

test:
  imports:
    - paraview
    - paraview.collaboration
    - paraview.coprocessing
    - paraview.cpexport
    - paraview.cpstate
    - paraview.lookuptable
    - paraview.numeric
    - paraview.numpy_support
    - paraview.python_view
    - paraview.cpstate
    - paraview.servermanager
    - paraview.simple
    - paraview.util

  commands:
    - pvpython --version
    - paraview --version

about:
   home: http://www.paraview.org
   license: BSD 3-Clause
   license_file: Copyright.txt
   summary: ParaView is an open-source, multi-platform data analysis and visualization application based on Visualization Toolkit (VTK).

extra:
  recipe-maintainers:
    - bgruening
    - jschueller
