{% set version = "6.0.1" %}
{% set maj_min = ".".join(version.split(".")[:2]) %}

package:
  name: paraview
  version: {{ version }}

source:
  url: https://paraview.org/files/v{{ maj_min }}/ParaView-v{{ version }}.tar.xz
  md5: 595ffe2aaf48c59d58414d284725ac91

  patches:
    # https://gitlab.kitware.com/cmake/cmake/-/issues/25079
    # vtkSMUndoStack.cxx.obj : error LNK2001: unresolved external symbol "private: void __cdecl absl::lts_20230125::log_internal::LogMessage::CopyToEncodedBuffer
    - absl.patch
    # override executable targets (VTK::WrapHierarchy, ParaView::ProcessXML, ...)
    - localuseroptions.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('paraview', max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libprotobuf                            # [build_platform != target_platform]
    - curl                                   # [build_platform != target_platform]
    - qt6-main                               # [build_platform != target_platform]
    - cmake
    - pkg-config
    - ninja
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - libgl-devel  # [linux]
    - libegl-devel  # [linux]
    - libglvnd-devel  # [linux]
    - vtk
    - python
    - libprotobuf
    - cgns
    - libboost-headers
    - libzip
    - libcurl
    - icu
    - libharu
    - libxml2-devel 2.14*
  run:
    - python
    - numpy
    - matplotlib-base  # [unix]

test:
  imports:
    - paraview
    - paraview.collaboration
    - paraview.coprocessing
    - paraview.numeric
    - paraview.numpy_support
    - paraview.python_view
    - paraview.servermanager
    - paraview.simple
    - paraview.util

  commands:
    - python -c "from paraview.simple import VisItNek5000Reader"  # [linux]
    - python -c "from paraview.simple import Xdmf3ReaderS"
    - pvpython --version
    - paraview --version  # [not linux]

about:
  home: http://www.paraview.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: Copyright.txt
  summary: ParaView is an open-source, multi-platform data analysis and visualization application based on Visualization Toolkit (VTK).

extra:
  recipe-maintainers:
    - vicentebolea
    - jschueller
