{% set version = "5.5.2" %}
{% set maj_min = ".".join(version.split(".")[:2]) %}

package:
  name: paraview
  version: {{ version }}

source:
  #fn: ParaView-v{{ version }}.tar.gz
  #url: http://paraview.org/files/v{{ maj_min }}/ParaView-v{{ version }}.tar.gz
  #sha256: 64561f34c4402b88f3cb20a956842394dde5838efd7ebb301157a837114a0e2d
  git_url: https://gitlab.kitware.com/paraview/paraview.git
  git_rev: v{{ version }}

build:
  number: 0
  # only enough time on circleci
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - eigen
  host:
    - python
    - libglu
    - hdf5
    - libpng
    - jpeg
    - libtiff
    - libxml2
    - zlib
    - freetype
    - twisted
    - autobahn
    - six
    - protobuf 3.5.*
    - lz4-c
    - zope.interface
    - expat
    - libogg
    - libtheora
    - libnetcdf
    - pugixml
    - mesalib
    - glew
  run:
    - python
    - libglu
    - hdf5
    - libpng
    - jpeg
    - libtiff
    - libxml2
    - zlib
    - freetype
    - twisted
    - autobahn
    - six
    - protobuf 3.5.*
    - lz4-c
    - zope.interface
    - expat
    - libogg
    - libtheora
    - libnetcdf
    - pugixml
    - mesalib
    - glew
    - numpy

test:
  imports:
    - paraview
    - paraview.annotation
    - paraview.calculator
    - paraview.collaboration
    - paraview.coprocessing
    - paraview.cpexport
    - paraview.cpstate
    - paraview.lookuptable
    - paraview.numeric
    - paraview.numpy_support
    - paraview.python_view
    - paraview.cpstate
    - paraview.servermanager
    - paraview.simple
    - paraview.util

  commands:
    - pvpython --version 2>&1 | grep paraview

about:
   home: http://www.paraview.org
   license: BSD 3-Clause
   license_file: Copyright.txt
   summary: ParaView is an open-source, multi-platform data analysis and visualization application based on Visualization Toolkit (VTK).

extra:
  recipe-maintainers:
    - bgruening
    - jschueller
