{% set version = "5.5.1" %}
{% set maj_min = ".".join(version.split(".")[:2]) %}

package:
  name: paraview
  version: {{ version }}

source:
  fn: ParaView-v{{ version }}.tar.gz
  url: http://paraview.org/files/v{{ maj_min }}/ParaView-v{{ version }}.tar.gz
  sha256: a6e67a95a7a5711a2b5f95f38ccbff4912262b3e1b1af7d6b9afe8185aa85c0d

build:
  number: 0
  # only enough time on circleci
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - eigen
    - python
    - libglu
    - hdf5 1.10.1
    - libpng >=1.6.32,<1.6.35
    - jpeg 9*
    - libtiff >=4.0.8,<4.0.10
    - libxml2 2.9.*
    - zlib 1.2.11
    - freetype 2.8.1
    - twisted
    - autobahn
    - six
    - protobuf 3.5.*
    - lz4-c
    - zope.interface
    - expat 2.2.*
    - libogg
    - libtheora
    - libnetcdf 4.4.*
    - pugixml
    - mesalib
    - glew
    - gcc  # [linux]
  run:
    - python
    - libglu
    - hdf5 1.10.1
    - libpng >=1.6.32,<1.6.35
    - jpeg 9*
    - libtiff >=4.0.8,<4.0.10
    - libxml2 2.9.*
    - zlib 1.2.11
    - freetype 2.8.1
    - twisted
    - autobahn
    - six
    - protobuf 3.5.*
    - lz4-c
    - zope.interface
    - expat 2.2.*
    - libogg
    - libtheora
    - libnetcdf 4.4.*
    - pugixml
    - mesalib
    - glew
    - numpy
    - libgcc  # [linux]

test:
  imports:
    - paraview
    - paraview.annotation
    - paraview.calculator
    - paraview.collaboration
    - paraview.coprocessing
    - paraview.cpexport
    - paraview.cpstate
    - paraview.lookuptable
    - paraview.numeric
    - paraview.numpy_support
    - paraview.pvvtkextensions
    - paraview.python_view
    - paraview.cpstate
    - paraview.servermanager
    - paraview.simple
    - paraview.util

  commands:
    - pvpython --version 2>&1 | grep paraview

about:
   home: http://www.paraview.org
   license: BSD 3-Clause
   license_file: Copyright.txt
   summary: ParaView is an open-source, multi-platform data analysis and visualization application based on Visualization Toolkit (VTK).

extra:
  recipe-maintainers:
    - bgruening
    - jschueller
