{% set version = "5.6.0" %}
{% set maj_min = ".".join(version.split(".")[:2]) %}

package:
  name: paraview
  version: {{ version }}

source:
  fn: ParaView-v{{ version }}.tar.gz
  url: http://paraview.org/files/v{{ maj_min }}/ParaView-v{{ version }}.tar.gz
  sha256: cb8c4d752ad9805c74b4a08f8ae6e83402c3f11e38b274dba171b99bb6ac2460

build:
  number: 1
  # only enough time on circleci
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - eigen
  host:
    - python
    - libglu
    - hdf5
    - libpng
    - jpeg
    - libtiff
    - libxml2
    - zlib
    - freetype
    - twisted
    - six
    - libprotobuf
    - lz4-c
    - zope.interface
    - expat
    - libogg
    - libtheora
    - libnetcdf
    - pugixml
    - mesalib
    - glew
    - double-conversion
  run:
    - python
    - libglu
    - hdf5
    - libpng
    - jpeg
    - libtiff
    - libxml2
    - zlib
    - freetype
    - twisted
    - six
    - libprotobuf
    - lz4-c
    - zope.interface
    - expat
    - libogg
    - libtheora
    - libnetcdf
    - pugixml
    - mesalib
    - glew
    - double-conversion
    - numpy

test:
  imports:
    - paraview
    - paraview.annotation
    - paraview.calculator
    - paraview.collaboration
    - paraview.coprocessing
    - paraview.cpexport
    - paraview.cpstate
    - paraview.lookuptable
    - paraview.numeric
    - paraview.numpy_support
    - paraview.python_view
    - paraview.cpstate
    - paraview.servermanager
    - paraview.simple
    - paraview.util

  commands:
    - pvpython --version 2>&1 | grep paraview

about:
   home: http://www.paraview.org
   license: BSD 3-Clause
   license_file: Copyright.txt
   summary: ParaView is an open-source, multi-platform data analysis and visualization application based on Visualization Toolkit (VTK).

extra:
  recipe-maintainers:
    - bgruening
    - jschueller
