{% set version = "5.10.1" %}
{% set maj_min = ".".join(version.split(".")[:2]) %}
{% set build_num = 7 %}

package:
  name: paraview
  version: {{ version }}

source:
  url: https://paraview.org/files/v{{ maj_min }}/ParaView-v{{ version }}.tar.xz
  md5: 0e1463ef95b4661b90e2ef4ea3c5182f

{% if build_variant == "qt" %}
{% set build_num = build_num + 100 %}
{% endif %}

build:
  number: {{ build_num }}
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build_num }}_{{ build_variant }}
  track_features:
    - paraview-egl  # [build_variant == "egl"]
  run_exports:
    - {{ pin_subpackage('paraview', max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libprotobuf                            # [build_platform != target_platform]
    - curl                                   # [build_platform != target_platform]
    - cmake
    - pkg-config
    - make  # [unix]
    - ninja  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}  # [build_variant == "egl"]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('mesa-libgbm') }}           # [linux]
    - {{ cdt('libxcb') }}                # [linux and build_variant == "egl"]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxrandr') }}             # [linux]
    - {{ cdt('alsa-lib') }}              # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
    - {{ cdt('libxt-devel') }}           # [linux]
    - {{ cdt('libsm-devel') }}           # [linux]
    - {{ cdt('libice-devel') }}          # [linux]
    - {{ cdt('libuuid-devel') }}         # [linux]
  host:
    - python
    - hdf4
    - hdf5
    - libpng
    - jpeg
    - libtiff
    - libxml2
    - zlib
    - freetype
    - libprotobuf
    - lz4-c
    - expat
    - libnetcdf
    - glew  # [build_variant == "qt"]
    - double-conversion
    - jsoncpp
    - xz
    - cgns  # [not win]
    - boost-cpp
    - pugixml
    - libtheora
    - gl2ps
    - qt-main  # [build_variant == "qt"]
    - libzip
    - libcurl
    - icu
    - eigen
  run:
    - python
    - numpy
    - matplotlib-base  # [unix]
    - twisted

test:
  imports:
    - paraview
    - paraview.collaboration
    - paraview.coprocessing
    - paraview.lookuptable
    - paraview.numeric
    - paraview.numpy_support
    - paraview.python_view
    - paraview.servermanager
    - paraview.simple
    - paraview.util

  commands:
    - python -c "from paraview.simple import VisItNek5000Reader"
    - python -c "from paraview.simple import Xdmf3ReaderS"
    - pvpython --version
    - paraview --version  # [not linux]

about:
  home: http://www.paraview.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: Copyright.txt
  summary: ParaView is an open-source, multi-platform data analysis and visualization application based on Visualization Toolkit (VTK).

extra:
  recipe-maintainers:
    - bgruening
    - jschueller
