{% set version = "5.13.2" %}
{% set maj_min = ".".join(version.split(".")[:2]) %}
{% set build_num = 8 %}

# TODO: drop this line after next version bump
{% set build_num = build_num + 100 %}  # [build_variant == "qt"]

package:
  name: paraview
  version: {{ version }}

source:
  url: https://paraview.org/files/v{{ maj_min }}/ParaView-v{{ version }}.tar.xz
  md5: c1c3883e0cab2d132e8a4d43f29873e9

  patches:
    # https://gitlab.kitware.com/cmake/cmake/-/issues/25079
    # vtkSMUndoStack.cxx.obj : error LNK2001: unresolved external symbol "private: void __cdecl absl::lts_20230125::log_internal::LogMessage::CopyToEncodedBuffer
    - absl.patch

    # https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11486
    - vtk_py313.patch

    # https://gitlab.kitware.com/paraview/paraview/-/issues/22806
    - ldflags.patch

build:
  number: {{ build_num }}
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ build_num }}_{{ build_variant }}
  track_features:
    - paraview-egl  # [build_variant == "egl"]
    - paraview-osmesa  # [build_variant == "osmesa"]
  run_exports:
    - {{ pin_subpackage('paraview', max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libprotobuf                            # [build_platform != target_platform]
    - curl                                   # [build_platform != target_platform]
    - qt6-main                               # [build_platform != target_platform]
    - cmake
    - pkg-config
    - ninja
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - libgl-devel  # [linux and build_variant != "osmesa"]
    - libegl-devel  # [build_variant == "egl"]
    - libglvnd-devel  # [linux and build_variant != "osmesa"]
    - mesalib  # [build_variant == "osmesa"]
    - glew  # [build_variant == "qt"]
    - qt6-main  # [build_variant == "qt"]
    - python
    - hdf5
    - libpng
    - libjpeg-turbo
    - libtiff
    - libxml2
    - zlib
    - freetype
    - libprotobuf
    - lz4-c
    - expat
    - libnetcdf
    - double-conversion
    - jsoncpp
    - liblzma-devel
    - cgns
    - libboost-headers
    - pugixml
    - libtheora
    - gl2ps
    - libzip
    - libcurl
    - icu
    - proj
    - libharu
    - liblzma-devel
  run:
    - python
    - numpy
    - matplotlib-base  # [unix]
    # because of gl2ps module
    - libgl  # [linux and build_variant == "osmesa"]

test:
  imports:
    - paraview
    - paraview.collaboration
    - paraview.coprocessing
    - paraview.numeric
    - paraview.numpy_support
    - paraview.python_view
    - paraview.servermanager
    - paraview.simple
    - paraview.util

  commands:
    - python -c "from paraview.simple import VisItNek5000Reader"  # [linux]
    - python -c "from paraview.simple import Xdmf3ReaderS"
    - pvpython --version
    - paraview --version  # [build_variant == "qt"]

about:
  home: http://www.paraview.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: Copyright.txt
  summary: ParaView is an open-source, multi-platform data analysis and visualization application based on Visualization Toolkit (VTK).

extra:
  recipe-maintainers:
    - bgruening
    - jschueller
