context:
  version: "6.1.0"
  maj_min: ${{ (version | split('.'))[:2] | join('.') }}

package:
  name: paraview
  version: ${{ version }}

source:
  url: https://paraview.org/files/v${{ maj_min }}/ParaView-v${{ version }}.tar.xz
  md5: 10de18a57e03673a9ca4b69954d4a6da

  patches:
    # https://gitlab.kitware.com/cmake/cmake/-/issues/25079
    # vtkSMUndoStack.cxx.obj : error LNK2001: unresolved external symbol "private: void __cdecl absl::lts_20230125::log_internal::LogMessage::CopyToEncodedBuffer
    - absl.patch

build:
  number: 3

requirements:
  build:
    - cmake
    - pkg-config
    - ninja
    - curl
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
  host:
    - vtk 9.6.1.*
    - vtk-io-ffmpeg
    - qt6-main
    - python
    - libprotobuf
    - cgns
    - libboost-headers
    - libzip
    - libcurl
    - icu
    - libharu
    - libxml2-devel 2.14*
    - zlib
    - if: linux
      then:
        - libgl-devel
        - libegl-devel
        - libglvnd-devel
  run:
    - python
    - numpy
    - if: unix
      then:
        - matplotlib-base
  run_exports:
    - ${{ pin_subpackage('paraview', upper_bound='x.x') }}

tests:
  - python:
      imports:
        - paraview
        - paraview.collaboration
        - paraview.coprocessing
        - paraview.numeric
        - paraview.numpy_support
        - paraview.python_view
        - paraview.servermanager
        - paraview.simple
        - paraview.util
  - script:
      - python -c "from paraview.simple import Xdmf3ReaderS"
      - pvpython --version
      - pvpython -c "import paraview.simple; from paraview import servermanager; assert servermanager.ProxyManager().GetPrototypeProxy('animation_writers', 'FFMPEG') is not None"
      - if: linux
        then: python -c "from paraview.simple import VisItNek5000Reader"
        else: paraview --version

about:
  homepage: http://www.paraview.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: Copyright.txt
  summary: ParaView is an open-source, multi-platform data analysis and visualization application based on Visualization Toolkit (VTK).

extra:
  recipe-maintainers:
    - vicentebolea
    - jschueller
