travis:
  secure:
    BINSTAR_TOKEN: rPLgrVd5weNPAZArvLB5Lp6VCg0j8UwVN+i7K71SAycnonqqT5zvBL6/pZAO5L0+XKt+oGpO/FEtFTiOtLeEgtG12yD+zt42FbWXpCUy+argMe81r2kT3yu14tJCaF2DwM0eK1VbKe1/92Ybh2giXple1plyjsy7O0prhSDB5DT6Z4lGfYta/AWi/lAnAPCEi5EgxRzx+1g/3gmC7YROE98Pg8y3ViLPDHiCtw59xl7762Mwn3xsY98VH0SiJ9Mi21lZpf7bSyOEmWmGe44RiFsmaGiMiIvMKRYAcvsWGSmn1hOVugB8ebIelyCzfyYhJSPxAVjR05X3U4TUsScgXR9GQogCbyvnlB8AOJZ/XDei9C21mAbFp4DdZlBjYm4wQcuNRgU8IFdhWMM/teCXfKrG5kAIe0z6Ts3yCKNBT6BpSeS8e2FVuPJVguiohyM/yMmMiCMpNSgzJo+HDl851CXL+CGbqL3OXIbTj4tOQSHruH0kPtaaTex3IrisjgYVdEUxb1gyfdamCH3ePq6jwjePcJW1XKPWRi+qjtebB8PFCq7oQCh2TjLo/5Hn6tDIlUkQQAW9EcQZ/OklDtJWP8rFwS7Mrj0tWtTrXNokJBz8Q/kekxFm3uWDKC1tKehrBJqNhmCnIKPW7Ll5UEjDXonP0zffo4VSQMqA2qa9E24=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  osx: azure
